import { BumdesUnitBusinessType, PrismaClient } from '@prisma/client';

export async function seedAccounts(prisma: PrismaClient) {
  const prismaAccountExtends = prisma.$extends({
    model: {
      account: {
        async createBatch(
          data: {
            groupRef: string;
            name: string;
            ref: string;
            isCredit: boolean;
            businessTypes: BumdesUnitBusinessType[];
          }[],
        ) {
          return await prisma.account.createMany({
            data: data.map((item) => ({
              name: item.name,
              ref: `${item.groupRef}-${item.ref}`,
              groupRef: item.groupRef,
              isCredit: item.isCredit,
              slug: item.name.toLowerCase().replace(/\s/g, '-'),
              businessTypes: item.businessTypes,
            })),
          });
        },
      },
    },
  });

  await prisma.accountGroup.createMany({
    skipDuplicates: true,
    data: [
      {
        name: 'Aset',
        ref: '1',
        slug: 'aset',
      },
      {
        name: 'Liabilitas',
        ref: '2',
        slug: 'liabilitas',
      },
      {
        name: 'Ekuitas',
        ref: '3',
        slug: 'ekuitas',
      },
      {
        name: 'Pendapatan',
        ref: '4',
        slug: 'pendapatan',
      },
      {
        name: 'Beban Pokok Penjualan',
        ref: '5',
        slug: 'beban-pokok-penjualan',
      },
      {
        name: 'Beban',
        ref: '6',
        slug: 'beban',
      },
      {
        name: 'Pendapatan Lainnya',
        ref: '7',
        slug: 'pendapatan-lainnya',
      },
      {
        name: 'Beban Lainnya',
        ref: '8',
        slug: 'beban-lainnya',
      },
    ],
  });

  await prismaAccountExtends.account.createBatch([
    {
      name: 'Kas',
      groupRef: '1',
      ref: '1001',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Rekening Bank',
      groupRef: '1',
      ref: '1002',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Giro',
      groupRef: '1',
      ref: '1003',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Piutang Usaha',
      groupRef: '1',
      ref: '1004',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Cadangan Kerugian Piutang',
      groupRef: '1',
      ref: '1005',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Persediaan Barang',
      groupRef: '1',
      ref: '1006',
      isCredit: false,
      businessTypes: ['COMMERCE'],
    },
    {
      name: 'Persediaan Barang Mentah',
      groupRef: '1',
      ref: '1006',
      isCredit: false,
      businessTypes: ['INDUSTRY'],
    },
    {
      name: 'Persediaan Barang Setengah Jadi',
      groupRef: '1',
      ref: '1007',
      isCredit: false,
      businessTypes: ['INDUSTRY'],
    },
    {
      name: 'Persediaan Barang Jadi',
      groupRef: '1',
      ref: '1008',
      isCredit: false,
      businessTypes: ['INDUSTRY'],
    },
    {
      name: 'Piutang Karyawan',
      groupRef: '1',
      ref: '1009',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Perlengkapan',
      groupRef: '1',
      ref: '1010',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Asuransi Dibayar di Muka',
      groupRef: '1',
      ref: '1011',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Sewa Dibayar di Muka',
      groupRef: '1',
      ref: '1012',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'PPN Masukan',
      groupRef: '1',
      ref: '1013',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pajak Dibayar Di Muka - PPh 23',
      groupRef: '1',
      ref: '1014',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pajak Dibayar Di Muka - PPh 25',
      groupRef: '1',
      ref: '1015',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Aset Lancar Lainnya',
      groupRef: '1',
      ref: '1016',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Aset Tetap - Tanah',
      groupRef: '1',
      ref: '2001',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Aset Tetap - Bangunan',
      groupRef: '1',
      ref: '2002',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Akumulasi Penyusutan - Bangunan',
      groupRef: '1',
      ref: '2012',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Aset Tetap - Kendaraan',
      groupRef: '1',
      ref: '2003',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Akumulasi Penyusutan - Kendaraan',
      groupRef: '1',
      ref: '2013',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Aset Tetap - Mesin',
      groupRef: '1',
      ref: '2004',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Akumulasi Penyusutan - Mesin',
      groupRef: '1',
      ref: '2014',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Aset Tetap - Peralatan Kantor',
      groupRef: '1',
      ref: '2005',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Akumulasi Penyusutan - Peralatan Kantor',
      groupRef: '1',
      ref: '2015',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Aset Tetap - Aset Sewa Guna Usaha',
      groupRef: '1',
      ref: '2006',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Akumulasi Penyusutan - Aset Sewa Guna Usaha',
      groupRef: '1',
      ref: '2016',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Hak Merek Dagang',
      groupRef: '1',
      ref: '3001',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Akumulasi Amortisasi : Hak Merek Dagang',
      groupRef: '1',
      ref: '3011',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Hak Cipta',
      groupRef: '1',
      ref: '3002',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Akumulasi Amortisasi : Hak Cipta',
      groupRef: '1',
      ref: '3012',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Good Will',
      groupRef: '1',
      ref: '3003',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Akumulasi Amortisasi : Good Will',
      groupRef: '1',
      ref: '3013',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Investasi',
      groupRef: '1',
      ref: '4000',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Usaha',
      groupRef: '2',
      ref: '1001',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Lain Lain',
      groupRef: '2',
      ref: '1002',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Gaji',
      groupRef: '2',
      ref: '1003',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pendapatan Diterima Di Muka',
      groupRef: '2',
      ref: '1004',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Konsinyasi',
      groupRef: '2',
      ref: '1005',
      isCredit: true,
      businessTypes: ['COMMERCE'],
    },
    {
      name: 'PPN Keluaran',
      groupRef: '2',
      ref: '1006',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Pajak - PPh 21',
      groupRef: '2',
      ref: '1007',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Pajak - PPh 23',
      groupRef: '2',
      ref: '1008',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Pajak - PPh 29',
      groupRef: '2',
      ref: '1009',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Pajak Lainnya',
      groupRef: '2',
      ref: '1010',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Kewajiban Lancar Lainnya',
      groupRef: '2',
      ref: '1011',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Kewajiban Manfaat Karyawan',
      groupRef: '2',
      ref: '1012',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Bank',
      groupRef: '2',
      ref: '2400',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Penyertaan Modal Desa',
      groupRef: '3',
      ref: '1001',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Cadangan  ',
      groupRef: '3',
      ref: '1002',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Bagi Hasil PADes',
      groupRef: '3',
      ref: '1012',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Dana Bantuan/Sumbangan/Hibah',
      groupRef: '3',
      ref: '1003',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Ikhtisar Laba Rugi Periode Berjalan',
      groupRef: '3',
      ref: '1004',
      isCredit: true,
      businessTypes: ['SERVICES'],
    },
    {
      name: 'Ikhtisar Laba Rugi',
      groupRef: '3',
      ref: '1004',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Pendapatan Jasa',
      groupRef: '4',
      ref: '1001',
      isCredit: true,
      businessTypes: ['SERVICES'],
    },
    {
      name: 'Pendapatan Penjualan',
      groupRef: '4',
      ref: '1001',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Diskon Penjualan',
      groupRef: '4',
      ref: '1011',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Retur Penjualan',
      groupRef: '4',
      ref: '1012',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Pendapatan Tiket',
      groupRef: '4',
      ref: '1002',
      isCredit: true,
      businessTypes: ['SERVICES'],
    },
    {
      name: 'Pendapatan Parkir',
      groupRef: '4',
      ref: '2001',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pendapatan Toilet',
      groupRef: '4',
      ref: '2002',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pendapatan Sewa',
      groupRef: '4',
      ref: '2003',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pendapatan Komisi',
      groupRef: '4',
      ref: '2004',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Pokok Penjualan',
      groupRef: '5',
      ref: '1001',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Diskon Pembelian',
      groupRef: '5',
      ref: '1101',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Retur Pembelian',
      groupRef: '5',
      ref: '1003',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Pengiriman & Pengangkutan',
      groupRef: '5',
      ref: '1004',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Beban Iklan & Promosi',
      groupRef: '6',
      ref: '1001',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Komisi & Fee',
      groupRef: '6',
      ref: '1002',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Bensin, Tol dan Parkir - Penjualan',
      groupRef: '6',
      ref: '1003',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Perjalanan Dinas - Penjualan',
      groupRef: '6',
      ref: '1004',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Komunikasi - Penjualan',
      groupRef: '6',
      ref: '1005',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Marketing Lainnya',
      groupRef: '6',
      ref: '1006',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Seragam Pegawai',
      groupRef: '6',
      ref: '1007',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Gaji',
      groupRef: '6',
      ref: '2001',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Upah',
      groupRef: '6',
      ref: '2002',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Makanan & Transportasi',
      groupRef: '6',
      ref: '2003',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Lembur',
      groupRef: '6',
      ref: '2004',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Pengobatan',
      groupRef: '6',
      ref: '2005',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban THR & Bonus',
      groupRef: '6',
      ref: '2006',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban BPJS - Kesehatan',
      groupRef: '6',
      ref: '2007',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban BPJS - Ketenagakerjaan',
      groupRef: '6',
      ref: '2008',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Insentif',
      groupRef: '6',
      ref: '2009',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Pesangon',
      groupRef: '6',
      ref: '2010',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Manfaat dan Tunjangan Lain',
      groupRef: '6',
      ref: '2011',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Bensin, Tol dan Parkir - Umum',
      groupRef: '6',
      ref: '2012',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Perbaikan & Pemeliharaan',
      groupRef: '6',
      ref: '2013',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Perjalanan Dinas - Umum',
      groupRef: '6',
      ref: '2014',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Konsumsi',
      groupRef: '6',
      ref: '2015',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Komunikasi - Umum',
      groupRef: '6',
      ref: '2016',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Iuran & Langganan',
      groupRef: '6',
      ref: '2017',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Asuransi',
      groupRef: '6',
      ref: '2018',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Legal & Profesional',
      groupRef: '6',
      ref: '2019',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Manfaat Karyawan',
      groupRef: '6',
      ref: '2020',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Sarana Kantor',
      groupRef: '6',
      ref: '2021',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Pelatihan & Pengembangan',
      groupRef: '6',
      ref: '2022',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Piutang Tak Tertagih',
      groupRef: '6',
      ref: '2023',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Pajak dan Perizinan',
      groupRef: '6',
      ref: '2024',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Denda',
      groupRef: '6',
      ref: '2025',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Listrik',
      groupRef: '6',
      ref: '2026',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Air',
      groupRef: '6',
      ref: '2027',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Langganan Software',
      groupRef: '6',
      ref: '2028',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Kantor',
      groupRef: '6',
      ref: '2029',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Alat Tulis Kantor & Printing',
      groupRef: '6',
      ref: '2030',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Bea Materai',
      groupRef: '6',
      ref: '2031',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Keamanan dan Kebersihan',
      groupRef: '6',
      ref: '2032',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Supplies dan Material',
      groupRef: '6',
      ref: '2033',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Sewa - Bangunan',
      groupRef: '6',
      ref: '2034',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Sewa - Kendaraan',
      groupRef: '6',
      ref: '2035',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Sewa - Operasional',
      groupRef: '6',
      ref: '2036',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Sewa - Lain - lain',
      groupRef: '6',
      ref: '2037',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Penyusutan - Bangunan',
      groupRef: '6',
      ref: '2038',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Penyusutan - Kendaraan',
      groupRef: '6',
      ref: '2039',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Penyusutan - Mesin',
      groupRef: '6',
      ref: '2040',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Penyusutan - Peralatan Kantor',
      groupRef: '6',
      ref: '2041',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Penyusutan - Aset Sewa Guna Usaha',
      groupRef: '6',
      ref: '2042',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Amortisasi : Hak Merek Dagang',
      groupRef: '6',
      ref: '2043',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Amortisasi : Hak Cipta',
      groupRef: '6',
      ref: '2044',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Amortisasi : Good Will',
      groupRef: '6',
      ref: '2045',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Pengeluaran Barang Rusak',
      groupRef: '6',
      ref: '2046',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Pendapatan dari Desa',
      groupRef: '7',
      ref: '1001',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pendapatan Bunga - Bank',
      groupRef: '7',
      ref: '1005',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pendapatan Bunga - Deposito',
      groupRef: '7',
      ref: '1006',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pendapatan Komisi - Barang Konsinyasi',
      groupRef: '7',
      ref: '1007',
      isCredit: true,
      businessTypes: ['COMMERCE'],
    },
    {
      name: 'Beban Bunga',
      groupRef: '8',
      ref: '1001',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: '(Laba)/Rugi Pelepasan Aset Tetap',
      groupRef: '8',
      ref: '1002',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Penyesuaian Persediaan',
      groupRef: '8',
      ref: '1003',
      isCredit: false,
      businessTypes: ['SERVICES'],
    },
    // TODO: Add after confirmation with accountant team
    // {
    //   name: 'Beban Denda', <-- duplicate
    //   groupRef: '8',
    //   ref: '1004',
    //   isCredit: false,
    //   businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    // },
    {
      name: 'Beban Pajak - Kini',
      groupRef: '8',
      ref: '1005',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Pajak - Tangguhan',
      groupRef: '8',
      ref: '1006',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
  ]);
}
