import {
  AccountType,
  BumdesUnitBusinessType,
  Prisma,
  PrismaClient,
} from '@prisma/client';

export async function seedAccounts(prisma: PrismaClient) {
  const prismaAccountExtends = prisma.$extends({
    model: {
      account: {
        async createBatch(
          data: {
            groupRef: string;
            subgroupRef: string;
            subgroupRefSlug: string;
            name: string;
            ref: string;
            isCredit: boolean;
            businessTypes: BumdesUnitBusinessType[];
          }[],
        ) {
          await prisma.account.createMany({
            data: data.map((item) => ({
              name: item.name,
              ref: `${item.groupRef}-${item.ref}`,
              subgroupRef: item.subgroupRefSlug,
              groupRef: item.groupRef,
              isCredit: item.isCredit,
              businessTypes: item.businessTypes,
              type: AccountType.GLOBAL,
            })),
          });
        },
      },
    },
  });

  await prisma.accountGroup.createMany({
    skipDuplicates: true,
    data: [
      {
        name: 'Aset',
        ref: '1',
      },
      {
        name: 'Liabilitas',
        ref: '2',
      },
      {
        name: 'Ekuitas',
        ref: '3',
      },
      {
        name: 'Pendapatan',
        ref: '4',
      },
      {
        name: 'Beban Pokok Penjualan',
        ref: '5',
      },
      {
        name: 'Beban',
        ref: '6',
      },
      {
        name: 'Pendapatan Lainnya',
        ref: '7',
      },
      {
        name: 'Beban Lainnya',
        ref: '8',
      },
    ],
  });

  const asetLancarSubGroup: Prisma.AccountSubgroupCreateManyInput = {
    groupRef: '1',
    ref: '1',
    name: 'Aset Lancar',
    refSlug: '1-1',
  };

  const asetTetapSubGroup: Prisma.AccountSubgroupCreateManyInput = {
    groupRef: '1',
    ref: '2',
    name: 'Aset Tetap',
    refSlug: '1-2',
  };

  const asetTidakBerwujudSubGroup: Prisma.AccountSubgroupCreateManyInput = {
    groupRef: '1',
    ref: '3',
    name: 'Aset Tidak Berwujud',
    refSlug: '1-3',
  };

  const asetLainnyaSubGroup: Prisma.AccountSubgroupCreateManyInput = {
    groupRef: '1',
    ref: '4',
    name: 'Aset Lainnya',
    refSlug: '1-4',
  };

  const liabilitasJangkaPendekSubGroup: Prisma.AccountSubgroupCreateManyInput =
    {
      groupRef: '2',
      ref: '1',
      name: 'Liabilitas Jangka Pendek',
      refSlug: '2-1',
    };

  const liabilitasJangkaPanjangSubGroup: Prisma.AccountSubgroupCreateManyInput =
    {
      groupRef: '2',
      ref: '2',
      name: 'Liabilitas Jangka Panjang',
      refSlug: '2-2',
    };

  const ekuitasSubGroup: Prisma.AccountSubgroupCreateManyInput = {
    groupRef: '3',
    ref: '1',
    name: 'Ekuitas',
    refSlug: '3-1',
  };

  const pendapatanOperasionalSubGroup: Prisma.AccountSubgroupCreateManyInput = {
    groupRef: '4',
    ref: '1',
    name: 'Pendapatan Operasional',
    refSlug: '4-1',
  };

  const pendapatanRupaRupaSubGroup: Prisma.AccountSubgroupCreateManyInput = {
    groupRef: '4',
    ref: '2',
    name: 'Pendapatan Rupa-rupa',
    refSlug: '4-2',
  };

  const bebanPokokPenjualanSubGroup: Prisma.AccountSubgroupCreateManyInput = {
    groupRef: '5',
    ref: '1',
    name: 'Beban Pokok Penjualan',
    refSlug: '5-1',
  };

  const bebanOperasionalSubGroup: Prisma.AccountSubgroupCreateManyInput = {
    groupRef: '6',
    ref: '1',
    name: 'Beban Operasional',
    refSlug: '6-1',
  };

  const bebanUmumDanAdministratifSubGroup: Prisma.AccountSubgroupCreateManyInput =
    {
      groupRef: '6',
      ref: '2',
      name: 'Beban Umum dan Administratif',
      refSlug: '6-2',
    };

  const pendapatanNonOperasionalSubGroup: Prisma.AccountSubgroupCreateManyInput =
    {
      groupRef: '7',
      ref: '1',
      name: 'Pendapatan Non Operasional',
      refSlug: '7-1',
    };

  const bebanNonOperasionalSubGroup: Prisma.AccountSubgroupCreateManyInput = {
    groupRef: '8',
    ref: '1',
    name: 'Beban Non Operasional',
    refSlug: '8-1',
  };

  await prisma.accountSubgroup.createMany({
    data: [
      asetLancarSubGroup,
      asetTetapSubGroup,
      asetTidakBerwujudSubGroup,
      asetLainnyaSubGroup,

      liabilitasJangkaPendekSubGroup,
      liabilitasJangkaPanjangSubGroup,

      ekuitasSubGroup,

      pendapatanOperasionalSubGroup,
      pendapatanRupaRupaSubGroup,

      bebanPokokPenjualanSubGroup,

      bebanOperasionalSubGroup,
      bebanUmumDanAdministratifSubGroup,

      pendapatanNonOperasionalSubGroup,
      bebanNonOperasionalSubGroup,
    ],
  });

  await prismaAccountExtends.account.createBatch([
    {
      name: 'Kas',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1001',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Rekening Bank',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1002',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Giro',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1003',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Piutang Usaha',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1004',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Cadangan Kerugian Piutang',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1005',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Persediaan Barang',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1006',
      isCredit: false,
      businessTypes: ['COMMERCE'],
    },
    {
      name: 'Persediaan Barang Mentah',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1006',
      isCredit: false,
      businessTypes: ['INDUSTRY'],
    },
    {
      name: 'Persediaan Barang Setengah Jadi',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1007',
      isCredit: false,
      businessTypes: ['INDUSTRY'],
    },
    {
      name: 'Persediaan Barang Jadi',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1008',
      isCredit: false,
      businessTypes: ['INDUSTRY'],
    },
    {
      name: 'Piutang Karyawan',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1009',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Perlengkapan',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1010',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Asuransi Dibayar di Muka',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1011',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Sewa Dibayar di Muka',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1012',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'PPN Masukan',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1013',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pajak Dibayar Di Muka - PPh 23',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1014',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pajak Dibayar Di Muka - PPh 25',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1015',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Aset Lancar Lainnya',
      groupRef: '1',
      subgroupRef: asetLancarSubGroup.ref,
      subgroupRefSlug: asetLancarSubGroup.refSlug,
      ref: '1016',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Aset Tetap - Tanah',
      groupRef: '1',
      subgroupRef: asetTetapSubGroup.ref,
      subgroupRefSlug: asetTetapSubGroup.refSlug,
      ref: '2001',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Aset Tetap - Bangunan',
      groupRef: '1',
      subgroupRef: asetTetapSubGroup.ref,
      subgroupRefSlug: asetTetapSubGroup.refSlug,
      ref: '2002',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Akumulasi Penyusutan - Bangunan',
      groupRef: '1',
      subgroupRef: asetTetapSubGroup.ref,
      subgroupRefSlug: asetTetapSubGroup.refSlug,
      ref: '2012',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Aset Tetap - Kendaraan',
      groupRef: '1',
      subgroupRef: asetTetapSubGroup.ref,
      subgroupRefSlug: asetTetapSubGroup.refSlug,
      ref: '2003',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Akumulasi Penyusutan - Kendaraan',
      groupRef: '1',
      subgroupRef: asetTetapSubGroup.ref,
      subgroupRefSlug: asetTetapSubGroup.refSlug,
      ref: '2013',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Aset Tetap - Mesin',
      groupRef: '1',
      subgroupRef: asetTetapSubGroup.ref,
      subgroupRefSlug: asetTetapSubGroup.refSlug,
      ref: '2004',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Akumulasi Penyusutan - Mesin',
      groupRef: '1',
      subgroupRef: asetTetapSubGroup.ref,
      subgroupRefSlug: asetTetapSubGroup.refSlug,
      ref: '2014',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Aset Tetap - Peralatan Kantor',
      groupRef: '1',
      subgroupRef: asetTetapSubGroup.ref,
      subgroupRefSlug: asetTetapSubGroup.refSlug,
      ref: '2005',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Akumulasi Penyusutan - Peralatan Kantor',
      groupRef: '1',
      subgroupRef: asetTetapSubGroup.ref,
      subgroupRefSlug: asetTetapSubGroup.refSlug,
      ref: '2015',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Aset Tetap - Aset Sewa Guna Usaha',
      groupRef: '1',
      subgroupRef: asetTetapSubGroup.ref,
      subgroupRefSlug: asetTetapSubGroup.refSlug,
      ref: '2006',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Akumulasi Penyusutan - Aset Sewa Guna Usaha',
      groupRef: '1',
      subgroupRef: asetTetapSubGroup.ref,
      subgroupRefSlug: asetTetapSubGroup.refSlug,
      ref: '2016',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Hak Merek Dagang',
      groupRef: '1',
      subgroupRef: asetTidakBerwujudSubGroup.ref,
      subgroupRefSlug: asetTidakBerwujudSubGroup.refSlug,
      ref: '3001',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Akumulasi Amortisasi : Hak Merek Dagang',
      groupRef: '1',
      subgroupRef: asetTidakBerwujudSubGroup.ref,
      subgroupRefSlug: asetTidakBerwujudSubGroup.refSlug,
      ref: '3011',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Hak Cipta',
      groupRef: '1',
      subgroupRef: asetTidakBerwujudSubGroup.ref,
      subgroupRefSlug: asetTidakBerwujudSubGroup.refSlug,
      ref: '3002',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Akumulasi Amortisasi : Hak Cipta',
      groupRef: '1',
      subgroupRef: asetTidakBerwujudSubGroup.ref,
      subgroupRefSlug: asetTidakBerwujudSubGroup.refSlug,
      ref: '3012',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Good Will',
      groupRef: '1',
      subgroupRef: asetTidakBerwujudSubGroup.ref,
      subgroupRefSlug: asetTidakBerwujudSubGroup.refSlug,
      ref: '3003',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Akumulasi Amortisasi : Good Will',
      groupRef: '1',
      subgroupRef: asetTidakBerwujudSubGroup.ref,
      subgroupRefSlug: asetTidakBerwujudSubGroup.refSlug,
      ref: '3013',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Investasi',
      groupRef: '1',
      ref: '4000',
      subgroupRef: asetLainnyaSubGroup.ref,
      subgroupRefSlug: asetLainnyaSubGroup.refSlug,
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Usaha',
      groupRef: '2',
      subgroupRef: liabilitasJangkaPendekSubGroup.ref,
      subgroupRefSlug: liabilitasJangkaPendekSubGroup.refSlug,
      ref: '1001',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Lain Lain',
      groupRef: '2',
      subgroupRef: liabilitasJangkaPendekSubGroup.ref,
      subgroupRefSlug: liabilitasJangkaPendekSubGroup.refSlug,
      ref: '1002',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Gaji',
      groupRef: '2',
      subgroupRef: liabilitasJangkaPendekSubGroup.ref,
      subgroupRefSlug: liabilitasJangkaPendekSubGroup.refSlug,
      ref: '1003',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pendapatan Diterima Di Muka',
      groupRef: '2',
      subgroupRef: liabilitasJangkaPendekSubGroup.ref,
      subgroupRefSlug: liabilitasJangkaPendekSubGroup.refSlug,
      ref: '1004',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Konsinyasi',
      groupRef: '2',
      subgroupRef: liabilitasJangkaPendekSubGroup.ref,
      subgroupRefSlug: liabilitasJangkaPendekSubGroup.refSlug,
      ref: '1005',
      isCredit: true,
      businessTypes: ['COMMERCE'],
    },
    {
      name: 'PPN Keluaran',
      groupRef: '2',
      subgroupRef: liabilitasJangkaPendekSubGroup.ref,
      subgroupRefSlug: liabilitasJangkaPendekSubGroup.refSlug,
      ref: '1006',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Pajak - PPh 21',
      groupRef: '2',
      subgroupRef: liabilitasJangkaPendekSubGroup.ref,
      subgroupRefSlug: liabilitasJangkaPendekSubGroup.refSlug,
      ref: '1007',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Pajak - PPh 23',
      groupRef: '2',
      subgroupRef: liabilitasJangkaPendekSubGroup.ref,
      subgroupRefSlug: liabilitasJangkaPendekSubGroup.refSlug,
      ref: '1008',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Pajak - PPh 29',
      groupRef: '2',
      subgroupRef: liabilitasJangkaPendekSubGroup.ref,
      subgroupRefSlug: liabilitasJangkaPendekSubGroup.refSlug,
      ref: '1009',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Pajak Lainnya',
      groupRef: '2',
      subgroupRef: liabilitasJangkaPendekSubGroup.ref,
      subgroupRefSlug: liabilitasJangkaPendekSubGroup.refSlug,
      ref: '1010',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Kewajiban Lancar Lainnya',
      groupRef: '2',
      subgroupRef: liabilitasJangkaPendekSubGroup.ref,
      subgroupRefSlug: liabilitasJangkaPendekSubGroup.refSlug,
      ref: '1011',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Kewajiban Manfaat Karyawan',
      groupRef: '2',
      subgroupRef: liabilitasJangkaPendekSubGroup.ref,
      subgroupRefSlug: liabilitasJangkaPendekSubGroup.refSlug,
      ref: '1012',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Utang Bank',
      groupRef: '2',
      subgroupRef: liabilitasJangkaPanjangSubGroup.ref,
      subgroupRefSlug: liabilitasJangkaPanjangSubGroup.refSlug,
      ref: '2400',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Penyertaan Modal Desa',
      groupRef: '3',
      subgroupRef: ekuitasSubGroup.ref,
      subgroupRefSlug: ekuitasSubGroup.refSlug,
      ref: '1001',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Cadangan  ',
      groupRef: '3',
      subgroupRef: ekuitasSubGroup.ref,
      subgroupRefSlug: ekuitasSubGroup.refSlug,
      ref: '1002',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Bagi Hasil PADes',
      groupRef: '3',
      subgroupRef: ekuitasSubGroup.ref,
      subgroupRefSlug: ekuitasSubGroup.refSlug,
      ref: '1012',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Dana Bantuan/Sumbangan/Hibah',
      groupRef: '3',
      subgroupRef: ekuitasSubGroup.ref,
      subgroupRefSlug: ekuitasSubGroup.refSlug,
      ref: '1003',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Ikhtisar Laba Rugi Periode Berjalan',
      groupRef: '3',
      subgroupRef: ekuitasSubGroup.ref,
      subgroupRefSlug: ekuitasSubGroup.refSlug,
      ref: '1004',
      isCredit: true,
      businessTypes: ['SERVICES'],
    },
    {
      name: 'Ikhtisar Laba Rugi',
      groupRef: '3',
      subgroupRef: ekuitasSubGroup.ref,
      subgroupRefSlug: ekuitasSubGroup.refSlug,
      ref: '1004',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Pendapatan Jasa',
      groupRef: '4',
      subgroupRef: pendapatanOperasionalSubGroup.ref,
      subgroupRefSlug: pendapatanOperasionalSubGroup.refSlug,
      ref: '1001',
      isCredit: true,
      businessTypes: ['SERVICES'],
    },
    {
      name: 'Pendapatan Penjualan',
      groupRef: '4',
      subgroupRef: pendapatanOperasionalSubGroup.ref,
      subgroupRefSlug: pendapatanOperasionalSubGroup.refSlug,
      ref: '1001',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Diskon Penjualan',
      groupRef: '4',
      subgroupRef: pendapatanOperasionalSubGroup.ref,
      subgroupRefSlug: pendapatanOperasionalSubGroup.refSlug,
      ref: '1011',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Retur Penjualan',
      groupRef: '4',
      subgroupRef: pendapatanOperasionalSubGroup.ref,
      subgroupRefSlug: pendapatanOperasionalSubGroup.refSlug,
      ref: '1012',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Pendapatan Tiket',
      groupRef: '4',
      subgroupRef: pendapatanOperasionalSubGroup.ref,
      subgroupRefSlug: pendapatanOperasionalSubGroup.refSlug,
      ref: '1002',
      isCredit: true,
      businessTypes: ['SERVICES'],
    },
    {
      name: 'Pendapatan Parkir',
      groupRef: '4',
      subgroupRef: pendapatanRupaRupaSubGroup.ref,
      subgroupRefSlug: pendapatanRupaRupaSubGroup.refSlug,
      ref: '2001',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pendapatan Toilet',
      groupRef: '4',
      subgroupRef: pendapatanRupaRupaSubGroup.ref,
      subgroupRefSlug: pendapatanRupaRupaSubGroup.refSlug,
      ref: '2002',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pendapatan Sewa',
      groupRef: '4',
      subgroupRef: pendapatanRupaRupaSubGroup.ref,
      subgroupRefSlug: pendapatanRupaRupaSubGroup.refSlug,
      ref: '2003',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pendapatan Komisi',
      groupRef: '4',
      subgroupRef: pendapatanRupaRupaSubGroup.ref,
      subgroupRefSlug: pendapatanRupaRupaSubGroup.refSlug,
      ref: '2004',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Pokok Penjualan',
      groupRef: '5',
      subgroupRef: bebanPokokPenjualanSubGroup.ref,
      subgroupRefSlug: bebanPokokPenjualanSubGroup.refSlug,
      ref: '1001',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Diskon Pembelian',
      groupRef: '5',
      subgroupRef: bebanPokokPenjualanSubGroup.ref,
      subgroupRefSlug: bebanPokokPenjualanSubGroup.refSlug,
      ref: '1101',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Retur Pembelian',
      groupRef: '5',
      subgroupRef: bebanPokokPenjualanSubGroup.ref,
      subgroupRefSlug: bebanPokokPenjualanSubGroup.refSlug,
      ref: '1003',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Pengiriman & Pengangkutan',
      groupRef: '5',
      subgroupRef: bebanPokokPenjualanSubGroup.ref,
      subgroupRefSlug: bebanPokokPenjualanSubGroup.refSlug,
      ref: '1004',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Beban Iklan & Promosi',
      groupRef: '6',
      subgroupRef: bebanOperasionalSubGroup.ref,
      subgroupRefSlug: bebanOperasionalSubGroup.refSlug,
      ref: '1001',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Komisi & Fee',
      groupRef: '6',
      subgroupRef: bebanOperasionalSubGroup.ref,
      subgroupRefSlug: bebanOperasionalSubGroup.refSlug,
      ref: '1002',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Bensin, Tol dan Parkir - Penjualan',
      groupRef: '6',
      subgroupRef: bebanOperasionalSubGroup.ref,
      subgroupRefSlug: bebanOperasionalSubGroup.refSlug,
      ref: '1003',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Perjalanan Dinas - Penjualan',
      groupRef: '6',
      subgroupRef: bebanOperasionalSubGroup.ref,
      subgroupRefSlug: bebanOperasionalSubGroup.refSlug,
      ref: '1004',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Komunikasi - Penjualan',
      groupRef: '6',
      subgroupRef: bebanOperasionalSubGroup.ref,
      subgroupRefSlug: bebanOperasionalSubGroup.refSlug,
      ref: '1005',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Marketing Lainnya',
      groupRef: '6',
      subgroupRef: bebanOperasionalSubGroup.ref,
      subgroupRefSlug: bebanOperasionalSubGroup.refSlug,
      ref: '1006',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Seragam Pegawai',
      groupRef: '6',
      subgroupRef: bebanOperasionalSubGroup.ref,
      subgroupRefSlug: bebanOperasionalSubGroup.refSlug,
      ref: '1007',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Gaji',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2001',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Upah',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2002',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Makanan & Transportasi',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2003',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Lembur',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2004',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Pengobatan',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2005',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban THR & Bonus',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2006',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban BPJS - Kesehatan',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2007',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban BPJS - Ketenagakerjaan',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2008',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Insentif',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2009',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Pesangon',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2010',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Manfaat dan Tunjangan Lain',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2011',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Bensin, Tol dan Parkir - Umum',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2012',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Perbaikan & Pemeliharaan',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2013',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Perjalanan Dinas - Umum',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2014',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Konsumsi',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2015',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Komunikasi - Umum',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2016',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Iuran & Langganan',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2017',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Asuransi',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2018',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Legal & Profesional',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2019',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Manfaat Karyawan',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2020',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Sarana Kantor',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2021',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Pelatihan & Pengembangan',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2022',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Piutang Tak Tertagih',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2023',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Pajak dan Perizinan',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2024',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Listrik',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2025',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Air',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2026',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Langganan Software',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2027',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Kantor',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2028',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Alat Tulis Kantor & Printing',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2029',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Bea Materai',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2030',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Keamanan dan Kebersihan',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2031',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Supplies dan Material',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2032',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Sewa - Bangunan',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2033',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Sewa - Kendaraan',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2034',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Sewa - Operasional',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2035',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Sewa - Lain - lain',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2036',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Penyusutan - Bangunan',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2037',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Penyusutan - Kendaraan',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2038',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Penyusutan - Mesin',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2039',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Penyusutan - Peralatan Kantor',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2040',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Penyusutan - Aset Sewa Guna Usaha',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2041',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Amortisasi : Hak Merek Dagang',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2042',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Amortisasi : Hak Cipta',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2043',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Amortisasi : Good Will',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2044',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Pengeluaran Barang Rusak',
      groupRef: '6',
      subgroupRef: bebanUmumDanAdministratifSubGroup.ref,
      subgroupRefSlug: bebanUmumDanAdministratifSubGroup.refSlug,
      ref: '2045',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Pendapatan dari Desa',
      groupRef: '7',
      subgroupRef: pendapatanNonOperasionalSubGroup.ref,
      subgroupRefSlug: pendapatanNonOperasionalSubGroup.refSlug,
      ref: '1001',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pendapatan Bunga - Bank',
      groupRef: '7',
      subgroupRef: pendapatanNonOperasionalSubGroup.ref,
      subgroupRefSlug: pendapatanNonOperasionalSubGroup.refSlug,
      ref: '1005',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pendapatan Bunga - Deposito',
      groupRef: '7',
      subgroupRef: pendapatanNonOperasionalSubGroup.ref,
      subgroupRefSlug: pendapatanNonOperasionalSubGroup.refSlug,
      ref: '1006',
      isCredit: true,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Pendapatan Komisi - Barang Konsinyasi',
      groupRef: '7',
      subgroupRef: pendapatanNonOperasionalSubGroup.ref,
      subgroupRefSlug: pendapatanNonOperasionalSubGroup.refSlug,
      ref: '1007',
      isCredit: true,
      businessTypes: ['COMMERCE'],
    },
    {
      name: 'Beban Bunga',
      groupRef: '8',
      subgroupRef: bebanNonOperasionalSubGroup.ref,
      subgroupRefSlug: bebanNonOperasionalSubGroup.refSlug,
      ref: '1001',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: '(Laba)/Rugi Pelepasan Aset Tetap',
      groupRef: '8',
      subgroupRef: bebanNonOperasionalSubGroup.ref,
      subgroupRefSlug: bebanNonOperasionalSubGroup.refSlug,
      ref: '1002',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Penyesuaian Persediaan',
      groupRef: '8',
      subgroupRef: bebanNonOperasionalSubGroup.ref,
      subgroupRefSlug: bebanNonOperasionalSubGroup.refSlug,
      ref: '1003',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY'],
    },
    {
      name: 'Beban Denda',
      groupRef: '8',
      subgroupRef: bebanNonOperasionalSubGroup.ref,
      subgroupRefSlug: bebanNonOperasionalSubGroup.refSlug,
      ref: '1004',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Pajak - Kini',
      groupRef: '8',
      subgroupRef: bebanNonOperasionalSubGroup.ref,
      subgroupRefSlug: bebanNonOperasionalSubGroup.refSlug,
      ref: '1005',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
    {
      name: 'Beban Pajak - Tangguhan',
      groupRef: '8',
      subgroupRef: bebanNonOperasionalSubGroup.ref,
      subgroupRefSlug: bebanNonOperasionalSubGroup.refSlug,
      ref: '1006',
      isCredit: false,
      businessTypes: ['COMMERCE', 'INDUSTRY', 'SERVICES'],
    },
  ]);
}
